[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://your-backend-domain.com"
  VITE_EMAILJS_SERVICE_ID = "your_production_service_id"
  VITE_EMAILJS_TEMPLATE_ID = "your_production_template_id"
  VITE_EMAILJS_PUBLIC_KEY = "your_production_public_key"
  VITE_API_KEY = "your_production_api_key"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://your-staging-backend.com"
  VITE_EMAILJS_SERVICE_ID = "your_staging_service_id"
  VITE_EMAILJS_TEMPLATE_ID = "your_staging_template_id"
  VITE_EMAILJS_PUBLIC_KEY = "your_staging_public_key"
  VITE_API_KEY = "your_staging_api_key" 