# Netlify部署配置
[build]
  publish = "dist"
  command = "npm run build"

# SPA路由重定向配置
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全头配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 